services:
  stem-backend:
    container_name: stem-backend
    build:
      context: ./backend
      dockerfile: DockerFile 
    # En producción no exponemos el puerto 8000 al mundo exterior. 
    #expose:
     # - "8000"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
    # queda pendiente el dominio
      CORS_ORIGINS: '["http://localhost", "https://tudominio.com"]'
      ENVIRONMENT: "production"

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: always
    networks:
      - stem-net

networks:
  stem-net:
    driver: bridge