version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/venv  # Evita que el venv local interfiera con el del contenedor
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Evita que los node_modules locales interfieran
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend