[pytest]
pythonpath = .
# modo asincrono 
asyncio_mode = auto 
# directorio de los testeos
testpaths = tests 

# Opciones por defecto de los testeos
addopts = 
    -v 
    --tb=short 
    --strict-markers

# Marcadores personalizados para los testeos
markers =
    asyncio: marca tests que usan async/await
    unit: pruebas unitarias
    integration: pruebas de integración
    functional: pruebas funcionales end-to-end

# Definicion de archivos de Py y sus rutas
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Warnings de las pruebas
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::sqlalchemy.exc.MovedIn20Warning
    ignore::pydantic.warnings.PydanticDeprecatedSince20