"""Add rss_url to organizaciones model

Revision ID: b84fb76a3bda
Revises: 6c862d4a86e6
Create Date: 2026-07-12 16:25:26.372768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84fb76a3bda'
down_revision: Union[str, None] = '6c862d4a86e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizaciones', sa.Column('rss_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizaciones', 'rss_url')
    # ### end Alembic commands ###
