"""New enfoque, tipo and imagen columns in Events model

Revision ID: 79572c502309
Revises: b84fb76a3bda
Create Date: 2026-07-13 14:41:28.459401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79572c502309'
down_revision: Union[str, None] = 'b84fb76a3bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('enfoque', sa.String(length=50), nullable=True))
    op.add_column('eventos', sa.Column('tipo', sa.String(length=50), nullable=True))
    op.add_column('eventos', sa.Column('imagen_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'imagen_url')
    op.drop_column('eventos', 'tipo')
    op.drop_column('eventos', 'enfoque')
    # ### end Alembic commands ###
