"""Add rss_alias field in organizacion model

Revision ID: 0bf01d719c09
Revises: a1b2c3d4e5f6
Create Date: 2026-07-20 21:49:04.020060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf01d719c09'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizaciones', sa.Column('rss_alias', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizaciones', 'rss_alias')
    # ### end Alembic commands ###
