"""added view column to event

Revision ID: 943510da531b
Revises: 137ad7cd6839
Create Date: 2026-07-28 07:37:54.811988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943510da531b'
down_revision: Union[str, None] = '137ad7cd6839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('vistas', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'vistas')
    # ### end Alembic commands ###
